services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - exchangerate.api_key=${EXCHANGERATE_API_KEY}

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
